Update README.md
zolamk/reviewpad-playground pull request #6
Opened 2022-11-04 12:47 UTC by zolamk

2022-11-04 12:47 UTC, zolamk commented
/reviewpad assign-reviewers zolamk,xulamek --total-reviewers=1 --review-policy=random

2022-11-11 11:54 UTC, xulamek requested changes

2022-11-11 11:54 UTC, xulamek commented on README.md
> +## Welcome!
let not do this but do this instead

2022-11-11 12:04 UTC, xulamek commented on README.md
>  To start using Reviewpad, check out the [Reviewpad GitHub Action](https://github.com/reviewpad/action).
another review

2022-11-11 12:35 UTC, xulamek approved these changes

2022-11-11 13:35 UTC, merged